### PR TITLE
use phobos style with dpldocs

### PR DESCRIPTION
**Pull request by wilzbach**
There are still a couple of bugs, but I guess one can see the direction.
I think it's mostly the links which don't work yet - [see it in action](http://docs.mir.dlang.io/phobos/test/).

__dont merge __ (Work in progress)

image

image

### CODE REVIEW

**Comment by 9il** [comment]
Why DDOX, but not DDOC? The last one is much more stable

**Comment by wilzbach** [comment]
I just copied the setup from dlang.org..

**Comment by 9il** [comment]
If DDOX is good enough then do not spend time on DDOC

**Comment by 9il** [comment]
This is real shame that D has not good out of the box docs

**Comment by wilzbach** [comment]
> If DDOX is good enough then do not spend time on DDOC

Well at least we can detect whether most macros are working correctly. It would be great to have a documentation as a service like many other languages do. 

I will continue to work on this once I find a bit of time again. My idea is now to be as close to the standard docs as possible for the ddoc macros.

**Comment by wilzbach** [comment]
superseded by #203

**Pull request closed without merging**
