### PR TITLE
Update travis.yml to send notifications to gitter + mail

### PR DESCRIPTION
**Pull request by wilzbach**

### CODE REVIEW

**Comment by 9il** [comment]
maybe just gitter without mail?
does it send to private gitter?

**Comment by 9il** [comment]
> maybe just gitter without mail?

Or this would send mails only on failures?

**Comment by wilzbach** [comment]
> maybe just gitter?

Idea was to shout loud if something crashes

> does it send to private gitter?

yes.

**Comment by wilzbach** [comment]
> Or this would send mails only on failures?

yep

**Comment by 9il** [comment]
ok

**Comment by wilzbach** [comment]
btw please wait - i will rebase

**Comment by 9il** [comment]
i can squash commits when make pr

**Pull request merged**
