### PR TITLE
README.md: use a version shield

### PR DESCRIPTION
**Pull request by wilzbach**
Might be nice to show the latest version instead.
There are a lot more shields for dub. 

http://shields.io/

Another good one is total downloads.

https://img.shields.io/dub/dt/mir.svg

However I don't know whether you want to show this while it is still low.

Total downloads

### CODE REVIEW

**Comment by 9il** [comment]
How it counts? Github shows 700+ clones https://github.com/DlangScience/mir/graphs/traffic

**Comment by wilzbach** [comment]
> How it counts? Github shows 700+ clones

That could be the CI.
I am afraid I don't know. Probably only the `dub` installs that are requested/proxied via code.dlang.org

**Comment by 9il** [comment]
> I am afraid I don't know. Probably only the dub installs that are requested/proxied via code.dlang.org
>  Show all checks

Ahaha, nobody uses mir :-).  No worries,  ndslice is a part of Phobos, and people probably use it with DMD.

**Comment by wilzbach** [comment]
> No worries, ndslice is a part of Phobos, and people probably use it with DMD.

Think so too - that's why I only proposed to use the version badge ;-)

**Comment by 9il** [comment]
Just add all three: latest version, license and total downloads :-)

**Comment by wilzbach** [comment]
> Just add all three: latest version, license and total downloads :-)

Updated!

**Comment by 9il** [comment]
Thanks!

**Pull request merged**
