### PR TITLE
Update appveyor.yml to use latest LDC and DUB

### PR DESCRIPTION
**Pull request by PetarKirov**

### CODE REVIEW

**Comment by PetarKirov** [comment]
I was reading http://wiki.dlang.org/Continuous_Integration (btw, nice work @wilzbach) and I stumbled upon: `...Should be removed once dub 0.9.26 is available`, so I wanted to test if the problem was resolved. I hope you don't mind :)

**Comment by wilzbach** [comment]
> so I wanted to test if the problem was resolved. I hope you don't mind

For mir we have another issue with ldc on windows - see #120 :/

**Comment by PetarKirov** [comment]
> For mir we have another issue with ldc on windows - see #120 :/

That's quite unfortunate, though it looks like the issue is not is not visible on [AppVeyor](https://ci.appveyor.com/project/9il/mir/build/1.0.105).

Should I leave `allow_failures` on for now?

**Comment by wilzbach** [comment]
> That's quite unfortunate, though it looks like the issue is not is not visible on AppVeyor.

Then I guess the bug got accidentally fixed. That's great news!

> Should I leave allow_failures on for now?

No no, better update the [compatibility table](https://github.com/libmir/mir#compatibility) later :)

@9il - let's go ahead & merge?

**Comment by PetarKirov** [comment]
It seems that the LDC [bug](https://github.com/ldc-developers/ldc/issues/1436) is still present, just encapsulated in a [try...catch](https://github.com/libmir/mir/blob/5067cc3b848170a79585dc737d8c8cb0349dbf95/source/mir/sum.d#L1865). You can see this on the output of the builds. The issue is only present with [LDC](https://ci.appveyor.com/project/9il/mir/build/1.0.105/job/avy1xu20cl8httjw#L63) (both 0.17 and 1.0.0).

Since @9il worked around the issue, I think it's better to leave the checks on, so LDC can get more extensive testing.

**Comment by PetarKirov** [comment]
> No no, better update the compatibility table

@wilzbach see PR https://github.com/libmir/mir/pull/229.

**Comment by 9il** [comment]
> It seems that the LDC bug is still present, just encapsulated in a try...catch. You can see this on the output of the builds. The issue is only present with LDC (both 0.17 and 1.0.0).

Thanks! Probably forgot to remove this block

**Comment by 9il** [comment]
see #230

**Comment by PetarKirov** [comment]
@9il so should I keep `allow_failures` for LDC or not?

**Comment by 9il** [comment]
> @9il so should I keep allow_failures for LDC or not?

Yes, keep please

**Comment by PetarKirov** [comment]
@9il Alright, fixed & rebased.

**Comment by PetarKirov** [comment]
Thanks

**Pull request merged**
