### PR TITLE
only run dub test on circleci

### PR DESCRIPTION
**Pull request by wilzbach**
follow-up to #112

### CODE REVIEW

**Comment by wilzbach** [comment]
Btw don't forgot to set CircleCI to `required` too ;-)

**Comment by 9il** [comment]
> Btw don't forgot to set CircleCI to required too ;-)
>  View details

I turned of this for me XP

**Comment by wilzbach** [comment]
> I turned of this for me XP

Is it possible to do this member-wise? 
So that I still have those constraints?

**Comment by 9il** [comment]
> Is it possible to do this member-wise? 
> So that I still have those constraints?

Yes, will turned off it for all

**Pull request merged**
