### PR TITLE
build examples on all platforms

### PR DESCRIPTION
**Pull request by wilzbach**
As we use this third-party library, I don't know whether it builds on Windows, but there is only one way to find out ;-)

### CODE REVIEW

**Comment by wilzbach** [comment]
Wohoo it does - @9il feel free to merge ;-)

**Comment by 9il** [comment]
Great! We also need to add this to travis.

**Comment by wilzbach** [comment]
> Great! We also need to add this to travis.

Already did - see
https://github.com/DlangScience/mir/pull/165/files

**Comment by 9il** [comment]
Cool!

**Pull request merged**
