### PR TITLE
improve code style

### PR DESCRIPTION
**Pull request by wilzbach**
mostly 120L, public properties, nicer numbers, ...

### CODE REVIEW

**Comment by 9il** [comment]
do not touch ndslice please )

**Comment by wilzbach** [comment]
> do not touch ndslice please )

oh I thought I have an open merge window :/
Should I submit these small changes of ndslice to Phobos then?

**Comment by wilzbach** [comment]
> do not touch ndslice please )

How should I proceed? #137 depends on this.

**Comment by 9il** [comment]
ok, will fix

**Comment by 9il** [comment]
but this first this should be merged: https://github.com/dlang/phobos/pulls?q=is%3Apr+is%3Aopen+label%3Andslice

**Comment by wilzbach** [comment]
> do not touch ndslice please )

Ok this just contains las + combinatorics, #137 excludes the `ndslice` directory :innocent:

**Pull request merged**
