### PR TITLE
notice about the NumPy - mir wiki entries

### PR DESCRIPTION
**Pull request by wilzbach**
as mentioned in issue #22

### CODE REVIEW

**Comment by 9il** [comment]
Thank you for the wiki! First we should feel already existing features.
For example `rollaxis` analog is `x.pack!2.evertPack.unpack`. `a = b` works too (if I am not wrong). Plus https://github.com/DlangScience/mir/wiki/NumPy:-Indexing can be easily implemented by user (see examples from https://dlang.org/phobos/std_experimental_ndslice_selection.html).

**Comment by wilzbach** [comment]
@9il - agreed that we shouldn't promote this as long as it is still in work ;-)
But let's keep this PR open, so that we don't forget it and can track our progress?

**Comment by 9il** [comment]
> But let's keep this PR open, so that we don't forget it and can track our progress?

of course

**Comment by wilzbach** [comment]
I changed my mind - let's put this as a task (see #77) and not as a PR ;-)

**Pull request closed without merging**
